### ISSUE TITLE
Get everyone on the Dojo Foundation CLA

### ISSUE THREAD

**Issue by cowboy** [gruntjs/grunt#1141]
### From now on, authors need to sign the [Dojo Foundation CLA](http://dojofoundation.org/about/claForm) before we can accept their PRs.

/cc @tkellen @vladikoff @shama @sindresorhus @jsoverson @jmeas @distilledhype

We're going to need to email a whole bunch of people pretty soon asking them to sign the [Dojo Foundation CLA](http://dojofoundation.org/about/claForm), so I've written a script to facilitate generating that list.

I haven't, however, written the email requesting people do that. But I've asked @vladikoff to help with that. I'm not sure exactly when the email will go out, but it will most likely be after an official blog post, and while I'm away on vacation. Of course. I still need to write that blog post.

Either way, here's how you generate the list. Also, feel free to use [count-commits](https://github.com/cowboy/dotfiles/blob/master/bin/count-commits) for other projects, suggest features, etc.

1. Create a temp folder and `cd` into it.
1. Run [clone-repos](https://github.com/gruntjs/clone-repos) to pull down all [57 (?) gruntjs org repos](https://github.com/gruntjs).
1. Run [count-commits](https://github.com/cowboy/dotfiles/blob/master/bin/count-commits) to collate commit info into something useful (aside: @shama y u so crazy? Kyle ☱☲☳☴☵☷ ☶ Robinson ☱☲ ☳☴☵☶☷ Young, really???)

Anyways:

```sh
$ count-commits > commits.txt
Error running "git log" in "grunt-lib-sourcemap" directory.
5876 commits by 466 authors in 56 projects.

# Also, FWIW, interesting
$ count-commits grunt > /dev/null
1275 commits by 47 authors in 1 project.

$ count-commits grunt-contrib-* > /dev/null
2795 commits by 330 authors in 30 projects.
```

And here's commits.txt as of tonight: https://gist.github.com/cowboy/88bc9d18174357e61160

**Comment by dmethvin** [comment]
To update this issue, anyone who has already signed the Dojo or jQuery CLAs is fine from a legal standpoint following the recent merger of the two foundations. 

For bookkeeping purposes the CLA bot that we'll be adding soon will ask anyone not on the jQuery Foundation CLA list to re-sign for any new work so your name is in that database. The first/last name and email of the commit should match the one that you sign at https://contribute.jquery.org/CLA/ so that it knows who you are.

A typical interaction with the bot goes [something like this](https://github.com/jquery/jquery/pull/2657) for a first-time contribution, and after that the bot never bothers you as long as your name/email doesn't change.

If there are former contributors who haven't yet signed the Dojo or jQuery Foundation CLAs, please head over to https://contribute.jquery.org/CLA/ and do so.

**Comment by jonschlinkert** [comment]
@dmethvin it might be helpful to those who aren't aware of what's happening to add a link to info about the merger (only on issues that seem pertinent)  [maybe this link](https://blog.jquery.com/2015/09/01/jquery-foundation-and-dojo-foundation-to-merge/)?: `https://blog.jquery.com/2015/09/01/jquery-foundation-and-dojo-foundation-to-merge/`
