### ISSUE TITLE
Broken Links in the 'Getting Started' section of the docs

### ISSUE THREAD

**Issue by cgcardona** [gruntjs/grunt#1273]
## Intro

Broken links in the [Getting Started section](http://gruntjs.com/getting-started) of your documentation.

## Details

At the top of the [Getting Started documentation](http://gruntjs.com/getting-started) there are 2 broken links (w/ the broken path):

* [Gruntfile example](http://sample-gruntfile/)
* [how to configure a task](http://configuring-tasks/)

### Expected behavior

I would expect that clicking either the `Gruntfile example` or the `how to configure a task` links would correctly resolve to the path. 

### Actual results

Once clicking the links they resolve to full `http` paths instead of presumably locally.

## Summary

Grunt is a slowly becoming critical to my workflow so I thank you for a great tool. :-]

**Comment by scurker** [comment]
This doesn't seem that this is an issue any longer, or at least the links listed on [Getting Started](https://github.com/gruntjs/grunt-docs/blob/master/Getting-started.md) seem to resolve to the correct path. If you do see this is an issue, it might be better to file an issue under [gruntjs/grunt-docs](https://github.com/gruntjs/grunt-docs/issues) since this repository is for the grunt core.

**Comment by dmethvin** [comment]
Yes, looks like this was fixed in https://github.com/gruntjs/grunt-docs/commit/013fbb33e5f25dc3169a58d0a2a924c923f03e43
