### ISSUE TITLE
Add FAQ entry about order of JavaScript enumerating objects.

### ISSUE THREAD

**Issue by cowboy** [gruntjs/grunt#132]
Given this config, it's likely that `grunt concat` will first build the `no_deps` target, followed by the `deps` target, but according to the [ES5 spec](http://es5.github.com/#x12.6.4), property enumeration order is _NOT guaranteed_.

``` javascript
grunt.initConfig({
  concat: {
    no_deps: {
      src: [
        'src/part1.js',
        'src/part2.js'
      ],
      dest: 'dist/built_no_deps.js'
    },
    with_deps: {
      src: [
        'vendor/dependency1.js',
        'vendor/dependency2.js',
        '<config:concat.no_deps.dest>'
      ],
      dest: 'dist/built_with_deps.js'
    }
  }
});
```

In case you don't trust Node.js or V8 to always iterate over object properties in the order in which they are defined, you could create an alias task that defines an explicit order, and reference that instead of the built-in task.

In this case, you would run `grunt build` instead of `grunt concat`.

``` javascript
grunt.registerTask('build', 'concat:no_deps concat:with_deps');
```

**Comment by avdd** [comment]
Has this come up as a FAQ since?

Coming from Python, where one never relies on property (dict key) ordering, I was surprised to read the behaviour of multi-tasks with *zero* mention of the implied ordering of properties.  Fair enough to rely on an implementation detail that is unlikely to change, but it would be sensible to point that out for those of us who instinctively note such things (and perhaps make judgements based on the omission).

**Comment by avdd** [comment]
See also http://stackoverflow.com/q/9179680
