### ISSUE TITLE
this.files.forEach ignores empty file sources / handling *no files* error in grunt.js

### ISSUE THREAD

**Issue by ducin** [gruntjs/grunt#1330]
I'm writing some grunt plugins. I'm using `this.files.forEach` to iterate over source files. This seems to be the recommended solution. The code of a task looks, more or less, like this:

    grunt.registerMultiTask(..., ..., function(){
      // init
      this.files.forEach(function (f) {
        // do something
      }
    });

`this.files`, console-logged, looks something like this:

```
[ { src: [Getter],
    dest: 'tmp/external-sources.json',
    orig: { src: [Object], dest: 'tmp/external-sources.json' } } ]
```

However I fell into trouble when there are no recognized source files. As far as I can see, the `this.files.forEach` iterates over existing files, so the `[Getter]` (don't know, what that is) doesn't execute an iteration for non-existent files.

Now, this is a problem for me, since I change file paths frequently. And if I misconfigure the new path, **I don't get notified** about invalid paths. The only way to handle this is to scan the long console output which is really frustrating for big projects. **I'd like to be notified when source list is empty**

----

The question is... in fact, the **questions** are:
 * how can I force grunt to shout, when there are no source files for a given task/target?
 * can I change this behavior globally? I mean, can I tell grunt to shout for empty source-list for all tasks?
 * did I I misunderstand something? If so, please, correct me.

----

Initially I've published the question on [stackoverflow](http://stackoverflow.com/questions/30264545/handling-no-files-error-in-grunt-js) but then I thought this is a better place to get a valuable answer...

**Comment by shama** [comment]
It's difficult because the src pattern `lib/*.js` cannot know that you hoped `lib/ithinkthisexists.js` should have existed.

You can supply `nonull: true` which won't ignore non-existent files: http://gruntjs.com/configuring-tasks#files

Otherwise your task can check `f.orig.src` which will contain the list of raw patterns fed to `src`. You can use [grunt.file.expand](http://gruntjs.com/api/grunt.file#grunt.file.expand) to try and expand the patterns and perform any comparison logic to determine which files are missing.
