### ISSUE TITLE
Fatal error: spawn cmd ENOENT

### ISSUE THREAD

**Issue by silentsnooc** [gruntjs/grunt#1389]
First I thought this was related to jsdoc but after I executed the command by hand it seems that this problem might come from grunt?

See [this issue](https://github.com/krampstudio/grunt-jsdoc/issues/152#issuecomment-149920097) I posted on grunt-jsdoc.

-------

I don't know what the problem is but as I run Grunt I'm getting this output here:

![capture](https://cloud.githubusercontent.com/assets/1429426/10590776/d60c55bc-76b2-11e5-9c1e-7424a56feb87.PNG)

I have tried deleting `bower_components` and `node_modules` and rerun `bower install & npm install` but that didn't resolve the issue like stated elsewhere.

Calling 

    node_modules\grunt-jsdoc\node_modules\.bin\jsdoc --configure jsdoc.conf.json --destination tmp/ --private --template node_modules\ink-docstrap/template js/controller.test.js js/view.test.js README.md package.json

by hand, I am not getting an error message or something. The documentation now appears to get build in `tmp\javascript_toy_cpu\1.0.0\`. It seems that jsdoc is working as it should.

In this case this issue relates to grunt but I have no idea what the problem could be.

------

Here is my `package.json` file:

```json
{
  "name": "javascript_toy_cpu",
  "version": "1.0.0",
  "description": "An implementation of the Princeton Toy CPU.",
  "main": "index.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {},
  "keywords": [
    "widget"
  ],
  "author": "blubb",
  "license": "Apache-2.0",
  "devDependencies": {
    "grunt": "^0.4.5",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-concat": "^0.5.1",
    "grunt-contrib-copy": "^0.8.2",
    "grunt-contrib-cssmin": "^0.14.0",
    "grunt-contrib-htmlmin": "^0.5.0",
    "grunt-contrib-jshint": "^0.11.3",
    "grunt-contrib-uglify": "^0.9.2",
    "grunt-jsdoc": "^1.0.0",
    "grunt-processhtml": "^0.3.8",
    "grunt-remove-calls": "0.0.6",
    "grunt-xmlpoke": "^0.8.0",
    "ink-docstrap": "^0.5.2",
    "requirejs": "^2.1.20"
  }
}
```

**Comment by shama** [comment]
This issue isn't related to Grunt. That task is calling `require('child_process').spawn` directly, see: https://github.com/krampstudio/grunt-jsdoc/blob/master/tasks/lib/exec.js#L53

While I don't the specific problem, the way that task is trying to lookup and spawn a remote command on the machine looks problematic. Also Windows requires a file extension in order for Node.js to spawn the binary.

My guess since you're getting `spawn cmd ENOENT` is that task simply cannot find the `jsdoc` binary it is looking for on your machine. `grunt-jsdoc` may want to look into using a library like this: https://www.npmjs.com/package/npm-execspawn in order to spawn a binary installed via npm in a platform safer way.

**Comment by silentsnooc** [comment]
Oh, alright. Thank you for the hint! :)

I'm going to use that I think.
