### ISSUE TITLE
Grunt needs your help!

### ISSUE THREAD

**Issue by cowboy** [gruntjs/grunt#1403]
We're looking for some help maintaining Grunt. Are you interested?

There are a number of specific things the project needs, such as:

* General `grunt` and `grunt-cli` maintenance
* Grunt contrib plugin maintenance
* Website / docs maintenance
* Issue triage
* New features (version 1.0? 2.0? The future!)

If you're interested, please reply in this thread. Let us know how you're interested in helping, and we'll figure out where to go from there. Thanks!

**Comment by arthurakay** [comment]
I'd be willing to help in just about any way.

**Comment by morkro** [comment]
I am interested :+1: 
I would like to help out with website/ docs maintenance, and plugin maintenance.

**Comment by dsalvagni** [comment]
:+1: I'm interested!

**Comment by tomapp** [comment]
I'm in! :+1:

**Comment by dustykeyboard** [comment]
I can help with website / docs.

**Comment by geoffdavis92** [comment]
I'd be interested in website/docs maintenance.

**Comment by rpdiss** [comment]
I can help too :+1:

**Comment by kaapa-s** [comment]
I'm in!

**Comment by Belciu** [comment]
I am interested!

**Comment by verpixelt** [comment]
Count me in for the website (docs).

**Comment by lelui12cr** [comment]
I can help with website (docs)

**Comment by scurker** [comment]
I've been looking for ways I can get more involved in open source projects, so I'm definitely interested! I think I'd be willing to help out wherever I could.

**Comment by danieltott** [comment]
I am also interested!

**Comment by dperrymorrow** [comment]
would be willing to help with anything, but website / docs I may be of most use.

**Comment by jshemas** [comment]
I'm very interested and would like to help!

**Comment by splurtcake** [comment]
I'm in!

**Comment by kaiquewdev** [comment]
Count me in!

**Comment by cyprianos** [comment]
I can help in maintaining:)

**Comment by mitchellsimoens** [comment]
Interested in helping with anything

**Comment by cyprianos** [comment]
I can help in maintenance.

**Comment by cyprianos** [comment]
I can help with grunt and grunt plugin maintenance.

**Comment by claudiamatosa** [comment]
I'd be willing to help. Particularly interested in new feature development, but would be happy to help in any of the other areas!

**Comment by callumsong** [comment]
Not sure if I'm capable but would love to help in anyway I can!

**Comment by matricore** [comment]
im here. pick me.

**Comment by educostachaves** [comment]
I wish!

**Comment by dancasttro** [comment]
I can help with website / docs too.

**Comment by svenkeeter** [comment]
sure... will help anyway i can

**Comment by padsbanger** [comment]
I can help with site and docs. Count me in !

**Comment by Server4001** [comment]
Willing to help with grunt, grunt-cli, contrib, site and docs!

**Comment by mattkime** [comment]
i'd love to pitch in where i can. 

this isn't the typical way of an open source project getting contributors but i kinda like it!

**Comment by sashashakun** [comment]
Ready to help anyway I can!

**Comment by cozzbie** [comment]
Sign me up

**Comment by zckly** [comment]
I'd like to help out with Docs!

**Comment by sapila** [comment]
Count me in gaiz...i ll try to help in any way!!

**Comment by iEgit** [comment]
It would be cool to participate, you may count on me

**Comment by ashwin-sureshkumar** [comment]
I would like to help in any manner.

**Comment by srs** [comment]
Great to see that so many people want to contribute. Grunt is a great project and I use it a lot. 

Will gladly help moving Grunt forward.

**Comment by greynaert** [comment]
I would be interrested too 👍🏻 in any way

**Comment by stefanjudis** [comment]
I'd be in for:

> General grunt and grunt-cli maintenance
> Grunt contrib plugin maintenance
> New features (version 1.0? 2.0? The future!)

:bowtie:

**Comment by Sqrcz** [comment]
I'm in for "Website / docs maintenance" anytime.

**Comment by cabaag** [comment]
I will help in any way as could be possible

**Comment by cmatskas** [comment]
Could you put the site on up-for-grabs.net and firsttimersonly.com so that people can easily pick up the tasks you need help with? And obviously, new contributors should be encouraged to help in any way possible. Thanks

**Comment by taggon** [comment]
I'm interested in plugin maintenance.

**Comment by alexcanessa** [comment]
Definetely I'm in.

**Comment by hoony** [comment]
I'd love to be in for any issues

**Comment by hoony** [comment]
I'm interested in 'grunt' and 'grunt-cli' maintenance.

**Comment by mkulinski** [comment]
I'd love to help wherever I can. My programming experience is limited but I can help with any documentation or basic front end needs.

**Comment by BenHaldenby** [comment]
Grunt has given so much, I'll give what I can.

**Comment by watilde** [comment]
I agree with above comment. I'm interesting in `grunt-cli` in particular!

**Comment by roperzh** [comment]
Count me to help in any area. :+1:

**Comment by gvsdan** [comment]
:+1: I'm interested!

**Comment by jacksonfdam** [comment]
I'm in. :beers:

**Comment by hguilla** [comment]
I'd like to help

**Comment by tomasAlabes** [comment]
I'm in.

**Comment by oxocode** [comment]
Count me in!

**Comment by funkage** [comment]
Reporting for site and/or docs maintenance duty, captain.

**Comment by lxibarra** [comment]
Give me something to do

**Comment by raphamorim** [comment]
I am interested in help on general grunt and grunt-cli maintenance :)

**Comment by Ppchiu** [comment]
I'm am interested in helping as well.

- General grunt and grunt-cli maintenance
- Grunt contrib plugin maintenance
- Issue triage
- New features

**Comment by maruf-nc** [comment]
I am interested

**Comment by boyomarinov** [comment]
I'd like to help as well

**Comment by b2m9** [comment]
website, docs, issues - no problem. wouldn't mind to contribute to grunt (but this would need some time).

**Comment by mejt** [comment]
I want to develop General grunt and grunt-cli maintenance

**Comment by sercaneraslan** [comment]
I'm interested

**Comment by qiuwanying** [comment]
I'm interested

**Comment by congdepeng** [comment]
I'm interested

**Comment by makky3939** [comment]
I'm interested.

**Comment by bomsy** [comment]
I'm interested in helping with the grunt-cli

**Comment by manmorjim** [comment]
I'm interested! I'll be busy next months but Grunt gives me so much so I'll give what I can! :smile:

**Comment by Hagendorn** [comment]
I'm also interested to contribute

**Comment by CristianoPassos** [comment]
Count with me!

**Comment by matallo** [comment]
Plus one here

**Comment by stradled** [comment]
Put me down to help - 

* Website Updates
* Issues

**Comment by mshmeirelles** [comment]
I'm also interested to contribute

**Comment by maxknee** [comment]
I'd like to help with issues, docs, maintenance

**Comment by juanbrujo** [comment]
:+1:  here, specially grunt and grunt-cli

**Comment by cmmata** [comment]
I can help too! As I see there are a lot of people than can help with web and docs, I can help with issue triage. I'm starting with node, so in no much time I could help too with maintenance (grunt, grunt-cli and grunt contrib plugin).

**Comment by slinto** [comment]
I'm interested.. Grunt is cool!

**Comment by wholysz** [comment]
I am interested in helping as well, as I would like to start to be a part of grunt's community. I can do grunt, grunt-cli maintanance, as well as work on new features.

**Comment by tnguyen14** [comment]
I am in.. written a grunt plugin myself, so still quite a noob, but hopefully can find my way around.

**Comment by danparm** [comment]
Still a Node and Grunt grasshopper. However I'm using Grunt more heavily at the company I work for and working it into our everyday development. Definitely interested in helping.

**Comment by wayspurrchen** [comment]
Also happy to pitch in a little here and there. I'm particularly fond of documentation but I can do maintenance work as well.

**Comment by froeba** [comment]
Yep, sign me up.  Can help with Grunt maintenance

**Comment by christopher-akins** [comment]
I'm definitely interested!

**Comment by duereg** [comment]
:+1:

**Comment by doron2402** [comment]
:+1:

**Comment by vladikoff** [comment]
What does :+1: mean in this case? are you happy to help with everything? some of it?

**Comment by karuto** [comment]
Count me in :+1:

**Comment by hyeomans** [comment]
:+1:

**Comment by JulienItard** [comment]
I could help with french translation

**Comment by kimwooglae** [comment]
I'm interested

**Comment by kasiriveni** [comment]
Definetely I'm in.

**Comment by ivanzhaowy** [comment]
I'm interested in impelementations of new features. I used grunt everywhere in my projects during every work, and I do have some feature requests about this great tool.

**Comment by fscherwi** [comment]
I'm interested to and will help where i can! :+1:

**Comment by ehhc** [comment]
I would be interested in helping as well. I would like to help in general grunt or grunt-cli maintenance but I haven't done a lot with node.js so I might not be that helpful...

**Comment by johnnonolan** [comment]
docs/some coding we use grunt a lot so it would be good to give back.

**Comment by Mark-Towndrow** [comment]
I'm interested

**Comment by Ykid** [comment]
program in nodejs for around 4 months full time. would like to help. could do some maintenance jobs.

**Comment by battaile** [comment]
I'd like to help,  Issue triage and handling minor issues initially.

**Comment by ntrphanikumar** [comment]
I would like to contribute too

**Comment by JulioMontas** [comment]
Hey I can help with the Website (Design) / docs maintenance and any design promotion to help GruntJS to keep growing for new users.

**Comment by hitenv** [comment]
Happy to help where I can

**Comment by abhi05b** [comment]
Willing to contribute... :)

**Comment by mflores88** [comment]
I would love to contribute with docs and website :)

**Comment by LuisRBarreras** [comment]
I'm interested

**Comment by jrcryer** [comment]
:+1:

**Comment by dmethvin** [comment]
Wow, thank you everyone! I'm closing this thread to new comments, but if you are interested and haven't commented please read on, it's never too late to contribute.

If you haven't done so already, please read the [contributing page](http://gruntjs.com/contributing). Most of the information there is relatively up to date and certainly enough to get things started. In particular, the #grunt-dev channel on IRC is a good place for real-time discussion and the contributing page can help you get started if you've never used IRC.

Now that [Grunt is part of the jQuery Foundation](https://blog.jquery.com/2015/09/01/jquery-foundation-and-dojo-foundation-to-merge/) we'll be switching to the [jQuery Foundation CLA](https://contribute.jquery.org/CLA/) so please sign there if you haven't yet. Soon we'll have a bot that checks pull requests to ensure that the contributor has signed the CLA. A typical interaction with the bot [looks like this](https://github.com/jquery/jquery/pull/2657) if you haven't yet signed. Be sure that the email and name use use on your git commits matches the one you use to sign the CLA.

So what about working on the project? For now I would anticipate a 0.4.6 that is a *very* conservative set of bug fixes and minor enhancements. Stuff is already tagged for that release but it seems like a *lot*, so if there is any doubt or a lack of someone to do the work it might be better to push it off until later.

For the longer term it seems safer to come out with Grunt 1.0.0 and start actually using Semver because anything but trivial changes will probably break a lot of existing Grunt setups. A good example is [this ticket about a message](https://github.com/gruntjs/grunt/pull/986). Grunt is used widely enough that even its messages can't be changed! At least with a major Semver bump people can be a little more prepared.

So, eager volunteers, here is what I recommend as a starting point:

* Triage the [open issues](https://github.com/gruntjs/grunt/issues). If the issue is unclear or the OP doesn't reply to questions, assume it's dead/stale. If an issue is really important, people will come back and make their case.
* Triage the [open pull requests](https://github.com/gruntjs/grunt/pulls). Some of them are years old and most likely can't be merged. Let's get that cleared up and find out what is really usable.
* Once we've assessed where we are, take unassigned issues and start creating pull requests.

When doing this work, it's best to spend some time looking at an issue and understanding where it was left off. Instead of just bumping a PR with a comment like "Does anyone know where this stands?" you could say, "I tried merging the PR with the current master and it's really out of date, lots of merge conflicts. Should we close this?"

Once it's clear who the active volunteers are over the next couple of weeks, we'll be trying to organize a more permanent team of people who can form the ongoing Grunt team. For the folks who volunteered to do docs and web sites, I think that work will lag the actual code work by a bit. Once we have the code under control there will definitely be a need to update things. Stay tuned!

**Comment by vladikoff** [comment]
For those who want to contribute with code / review / testing, here are two pull requests:

* "Add support for Gruntfile.babel.js" - https://github.com/gruntjs/grunt/pull/1368 Could you review this PR or test this with your babel project?
* "Update findup-sync to 0.3.0 and lodash to 3.10.1" - https://github.com/gruntjs/grunt/pull/1406/files Same thing, could you pull in that particular version and see if it breaks anything. Large projects that use Grunt would be helpful for testing.

Feel free to comment in those issues. Let me know in those issues if you have any questions.
