### ISSUE TITLE
glob issue in 1.0.0-rc1

### ISSUE THREAD

**Issue by steveoh** [gruntjs/grunt#1461]
With [grunt-contrib-jasmine](https://github.com/gruntjs/grunt-contrib-jasmine) and a target like 

```js
        jasmine: {
            main: {
                options: {
                    specs: ['src/app/**/Spec*.js'],
                    host: 'http://localhost:8000'
                }
            }
        }
```

grunt errors with `Warning: glob pattern string required Use --force to continue.`

This seems like a grunt issue since the jasmine plugin does not depend on glob.

**Comment by shama** [comment]
Looks like this is because of this line: https://github.com/gruntjs/grunt-contrib-jasmine/blob/master/tasks/lib/jasmine.js#L129

It's calling the lodash wrapper sequence without ending using `.value()`:

```js
grunt.util._(patterns).compact()
```

should be

```js
grunt.util._(patterns).compact().value()
```

Otherwise it tries to pass the `LodashWrapper` to the glob:

<img width="803" alt="screen shot 2016-02-13 at 11 56 44 am" src="https://cloud.githubusercontent.com/assets/99604/13029748/afc764bc-d249-11e5-93a0-1afaeba4ca51.png">
