### ISSUE TITLE
Grunt Aborted due to timeout

### ISSUE THREAD

**Issue by robin-obrien** [gruntjs/grunt#1468]
I am running a task via grunt-exec that works fine without grunt. When running with grunt it starts fine, but after 5-10 minutes it fails, with the following stack trace. It seems as some timer reaches a timeout. Please don't pay extra attention to the tasks names.

```
Warning: Task "exec:xyz" failed. Use --force to continue.
Error: Task "exec:xyz" failed.
    at Task.<anonymous> (project/node_modules/grunt/lib/util/task.js:205:15)
    at null._onTimeout (project/node_modules/grunt/lib/util/task.js:241:33)
    at Timer.listOnTimeout (timers.js:92:15)
```
My node version is v4.3.1, grunt version grunt-cli: v0.1.13, grunt: v0.4.5, casperjs: 1.1.0-beta5

**Comment by shama** [comment]
Consider the following example:

```js
grunt.registerTask('works', function () {
  var done = this.async();
  done(false);
});
```

If you run `grunt works --stack` you'll get the following:

```shell
$ grunt works --stack
Running "works" task
Warning: Task "works" failed. Use --force to continue.
Error: Task "works" failed.
    at Task.<anonymous> (/Users/Kyle/Documents/www/test/node_modules/grunt/lib/util/task.js:205:15)
    at null._onTimeout (/Users/Kyle/Documents/www/test/node_modules/grunt/lib/util/task.js:241:33)
    at Timer.listOnTimeout (timers.js:92:15)
```

Grunt is not timing out but rather an async task is purposely failing the task `done(false)`. The stack trace is misleading because the task is relying on [Grunt to report the error](https://github.com/gruntjs/grunt/blob/master/lib/util/task.js#L207).

The `grunt-exec` task [purposely fails the task in this way](https://github.com/jharding/grunt-exec/blob/master/tasks/exec.js#L62) when a binary it has executed has errored.

---

This is what is happening:

* Grunt runs the `exec` task.
* `grunt-exec` spawns a child process to `casperjs`
* `casperjs` times out, reports an error to `stderr`
* `grunt-exec` gets that error, logs it and fails the Grunt task
* Grunt reports that error

---

The failure is not at Grunt's fault and Grunt itself doesn't have a timeout on tasks. If running `casperjs` without `grunt-exec` works, I recommend looking into why spawning `casperjs` as a child process in Node.js in the way that `grunt-exec` does might cause an issue. Or perhaps `casperjs` is succeeding but failing to exit the process in way `grunt-exec` deems successful. There could be a number of reasons for `casperjs` to fail or timeout.

In either case, this isn't an issue with Grunt.

**Comment by robin-obrien** [comment]
Thanks for the detailed response, I really appreciate that!
I went over to find a youtube on, as I am new with JavaScript (More of a java dev) and the first video I found was: https://www.youtube.com/watch?v=9o8B3L0-d9c. Great one.

One last question, if I may, what would be your recommendation for a root cause analysis. try and catch events within the grunt-exec code? I've placed try and catch in my casperjs code, but nothing got caught.

Thanks!

**Comment by shama** [comment]
@robin-obrien You can try replacing the `done(false)` calls in `grunt-exec` to `done(err)`. If you [pass an error](https://github.com/gruntjs/grunt/blob/master/lib/util/task.js#L209) to the `done()` call, it will fail the task but use the error provided, rather than Grunt generating one. That may give you a better stack trace.

Otherwise copy the `require('child_process').exec` portions from that task into a script to spawn `casperjs`. Then log the `stderr` and `stdout` and exit code to see how exactly `casperjs` is spawned.

You might have better luck finding another task on npm specifically for running `casperjs` too.
