### ISSUE TITLE
Event.on namespace

### ISSUE THREAD

**Issue by andresz1** [gruntjs/grunt#1516]
I'm trying to catch event on of 2 watch tasks, but it doesn't work. Can you check it please, I would appreciate any help. Here is the code:

```js
watch: {
  src: {
    files: [paths.src.main, paths.src.all],
    tasks: ['babel'],
    options: {
      spawn: false,
    },
  },
  srcno: {
    files: paths.src.no,
    tasks: ['copy'],
    options: {
      spawn: false,
    },
  },
}

// ...

// Doesn't work
grunt.event.on(['watch.src'], function(action, filepath) {
  console.log(action);
  grunt.config('babel.src.files.0.src', filepath);
});

// Doesn't work either
grunt.event.on(['watch', 'nosrc'], function(action, filepath) {
  console.log(action);
  grunt.config('copy.srcno.files.0.src', filepath);
});
```
Thank you!

**Comment by shama** [comment]
`grunt-contrib-watch` only [emits a `watch` event](https://github.com/gruntjs/grunt-contrib-watch#using-the-watch-event). Although the problem with events is you don't know when they'll fire or complete. Meaning if you `grunt.config` in an event, the `babel` task may have already been started by the watch task and will use the config before the event changes it.

Instead of using `grunt.event` (which was never fully implemented and will likely be deprecated and removed down the road), use a task instead:

```js
watch: {
  src: {
    files: [paths.src.main, paths.src.all],
    tasks: ['before:babel', 'babel'],
    options: {
      spawn: false,
    },
  },
  srcno: {
    files: paths.src.no,
    tasks: ['before:copy', 'copy'],
    options: {
      spawn: false,
    },
  },
}

// ...

grunt.registerTask('before', function (task) {
  // Determine which files need to be set
  grunt.config([task, 'target', 'src'], filePatterns);
});
```

[grunt-newer](https://www.npmjs.com/package/grunt-newer) pretty much does this already but with tasks, we can expect the same order every time.

**Comment by andresz1** [comment]
Thank you!
