### ISSUE TITLE
Grunt on LXD Container -  src/unix/linux-core.c:747: read_times: Assertion `num == numcpus' failed.

### ISSUE THREAD

**Issue by madhairsilence** [gruntjs/grunt#1646]
Grunt build fails with the following message
```
Verifying property concurrent.dist exists in config...OK
Files: [no src] -> dist
grunt: src/unix/linux-core.c:747: read_times: Assertion `num == numcpus' failed.
Aborted (core dumped)

```
This does not happen on AWS or Local machine. But only in an LXD Container. Any clue?

**Comment by shama** [comment]
I'm not familiar with lxd containers sorry.

**Comment by madhairsilence** [comment]
@shama So "It wont work in LXD Container" is the answer?

**Comment by shama** [comment]
@madhairsilence Yes that is the answer. Issues are reserved for issues with Grunt. This is not a support channel. Some times I do volunteer my _free time_ to answer support questions, if I am familiar with them.

You are free to volunteer your time researching your issue and if you discover it actually is because of an issue in Grunt, then reopen this issue or open a new one. Or move your stack to gulp, it's your stack, not mine. Here is a link: https://github.com/gulpjs/gulp Good luck!

**Comment by vladikoff** [comment]
Also the problem is in the `concurrent` plugin, not in core. 

Per

> Verifying property concurrent.dist

**Comment by madhairsilence** [comment]
@shama  "issues are related to grunt ?" what did  I post about? "GRUNT" in LXD Container.  And what do you mean by "This is not a support channel" . I never asked you to do my homework. And whatever I said is an *Issue* as mentioned by @vladikoff , its the problem with concurrent. And fortunately fixed it. Next if "YOU" are not familiar, please be quiet and ignore the question. Let some knowledgeable person answer the queries.
