### ISSUE TITLE
fsevents optional dependency removal?

### ISSUE THREAD

**Issue by benjaminhowarth1** [gruntjs/grunt#1656]
As fsevents is a Mac-only module, and an optional dependency, two questions:
1) is it really needed?
2) if it is essential for Grunt functionality, would it not be sensible to replace with chokidar, which is cross-platform?

Will start a fork/branch to investigate, with a view to sending a PR in.

**Comment by shama** [comment]
Both Grunt and grunt-contrib-watch don't have `fsevents` as a dependency. I would double check your dependencies.

chokidar, however, does have `fsevents` as an optional dependency: https://github.com/paulmillr/chokidar/blob/master/package.json#L43 So maybe you have another dependency that loads `fsevents` in your tree?

As for using chokidar for grunt-contrib-watch, it has been discussed and attempted many times over the years. Unfortunately each time chokidar didn't cover all the behaviors that gaze covers. You can search the watch repo to see the previous discussions: https://github.com/gruntjs/grunt-contrib-watch/search?q=chokidar&type=Issues I'm not sure if things have changed since those discussions though.

**Comment by benjaminhowarth1** [comment]
So when I install grunt into a brand-new npm project, the fsevents gets mentioned as a WARN as an optional dependency.
This is on Windows 10 x64.
This is even if there are no other items in the package.json, leading me to believe that grunt has a soft dependency on fsevents.

**Comment by shama** [comment]
Ah ha, you're right. It looks like `tiny-lr` (which `grunt-contrib-watch` has as a dependency) now has `chokidar` as a dependency. That is used for live reload in `grunt-contrib-watch`. FWIW, if you're not on a Mac, that dependency just doesn't get installed. You can ignore it.

Also `grunt-contrib-watch` is optional too. There are lots of other watch tasks and some that use chokidar instead too. Give them a try and use which ever works best for you.

**Comment by benjaminhowarth1** [comment]
I get that you can ignore fsevents on non-Mac systems, I just don't think that it should show up at all.
To reiterate: this is grunt, clean on a Windows 10 x64 system, no other modules installed, throwing a WARN on fsevents as a soft dependency.
If it's necessary for Mac, fine, but if it's needed overall for grunt, it should be replaced, or the WARN downgraded to an INFO or similar on non-Mac systems.

**Comment by shama** [comment]
Re: `WARN` vs `INFO` for `optionalDependencies` that is handled by npm and out of our control. You would need to open an issue on their board and make your case there.

Grunt itself doesn't have `fsevents` as a dependency, `grunt-contrib-watch` does. That is an optional task and there are many other watch tasks to choose from if that one doesn't suit your needs.

Replacing `tiny-lr` in `grunt-contrib-watch` to avoid an ignorable warning doesn't sound worth the time IMO. Closing as wont fix.
