### ISSUE TITLE
Revert mkdirp upgrade

### ISSUE THREAD

**Issue by DanielRuf** [gruntjs/grunt#1707]
Please revert https://github.com/gruntjs/grunt/commit/f1898ebe7779bc3bc99e82ddf80920573acf94ef and the other changes regarding the node requirement. And make a proper major release.

This is a breaking change because now grunt supports only Node 8+.

https://travis-ci.org/github/gruntjs/grunt/builds/662764498
https://travis-ci.org/github/gruntjs/grunt/builds/662764550
https://ci.appveyor.com/project/gruntjs/grunt/builds/31480852

See also https://github.com/isaacs/node-mkdirp/issues/2

Now grunt does not follow SemVer anymore because of this and this causes a failing build of https://github.com/DanielRuf/html-minifier-terser which is used in https://github.com/jantimon/html-webpack-plugin and webpack 4 still supports node 6+.

For the time being I will pin the grunt version.

**Comment by BojanJakic** [comment]
Hello there,
I'm working on one project and have problem with _Jenkins_ build, this is peace from error log:
`mkdirp@0.5.3: Legacy version of mkdirp are no longer supported. Please update to mkdirp 1.x.`
Guys that works with _Jenkins_ think this happens because _grunt v1.1.0_ does not support _mkdirp 0.5.x_ , some libraries from project requires _mkdirp 0.5.x_ and grunt fails to run some tasks
I'm wondering is there any known issue related to described problem? Maybe some older version of grunt can solve it?
Sorry if this issue is wrong place for this question
Cheers...

**Comment by vladikoff** [comment]
> I'm wondering is there any known issue related to described problem? Maybe some older version of grunt can solve it?

@BojanJakic you can try downgrading the Grunt version 

However the mkdirp warning could be coming from elsewhere

**Comment by DanielRuf** [comment]
> mkdirp@0.5.3: Legacy version of mkdirp are no longer supported. Please update to mkdirp 1.x.

You can safely ignore the warning, this breaks nothing. Also please open a new issue regarding your problem.

**Comment by DanielRuf** [comment]
All 0.x versions were marked as deprectaed but the latest 0.5.3 fixes the vulnerability because others also need support for older Node versions.
