### ISSUE TITLE
Any PhantomJS timeouts with Qunit plugin?

### ISSUE THREAD

**Issue by creynders** [gruntjs/grunt#219]
@cowboy Have you encountered this issue with the Qunit task? creynders/grunt-jasmine-task#4
I'm getting multiple complaints about phantomjs timing out, but all barebones versions they provide me with work on my setup.
The jasmine plugin was largely based on your QUnit plugin and calls phantomjs in largely the same fashion, so it puzzles me that I haven't seen any of these issues with your Qunit plugin.

**Comment by ernsheong** [comment]
Any fixes for this? Facing this issue with RequireJS

**Comment by charlievaughan** [comment]
I've been working to fix a similar problem related to the `Warning: PhantomJS timed out, possibly due to an unfinished async spec. Use --force to continue` error.

I'd thought this was due the Jasmine async tests we had been using combined with PhantomJS / Grunt / grunt-contrib-jasmine. But after a LOT of time and investigation I found it was related to the way some of our tests were being cleaned up:

```
afterEach(function () {
    $body.empty();
});
```

In this instance we were emptying all the elements injected into the DOM for the test. But this doesn't unbind all the JS code which lingers in the background and causes PhantomJS to eventually timeout. This blocked further Grunt tasks from running reports.

This is the better technique:

```
afterEach(function () {
    $element.remove();
    $nav.remove();
});
```

Elements added to the DOM should be removed individually to ensure all the JS associated with them is properly removed and cleaned up, ready for the next spec.

This meant we could have a large stack of 77 specs complete without PhantomJS timing out.
