### ISSUE TITLE
Get rid of "global" plugins.

### ISSUE THREAD

**Issue by cowboy** [gruntjs/grunt#438]
The reason that global grunt plugins exist was to basically provide an easy way for task authors to bundle their custom tasks and init templates in a single easy-to-install package. That plugin would include grunt internally, as a dependency, and would thus have access to everything grunt had to offer, plus some extra stuff.

The problem with this, of course, is that globally installing one version of a thing-that-has-multiple-versions is irreconcilable with working on multiple projects that require different versions of that thing. If you have plugin-foo v1.0.0 installed globally, project bar that requires plugin-foo v1.0.0 will work great, but project baz that requires plugin-foo v1.5.0 won't necessarily work great.

This problem is already addressed in npm by installing npm modules locally. If the project-appropriate version of plugin-foo is installed local to projects bar and baz, there are no problems.

Of course, this doesn't work with init templates, because since init templates are used to **create** projects, they _need to exist somewhere already_. Which means that init templates can't be installed as npm modules.

Which brings me to the `grunt.npmTasks` method. It was created for use in grunt plugins that will be installed globally. It's a total hack created back when I thought grunt was going to be installed globally, and not locally. It tells grunt to load tasks bundled with the plugin as a dependency. This method has to go.

Of course, it can only be removed if there is, in fact, an alternative to globally installed plugins. Which there will be when the `init` task is improved to load templates dynamically. See #239.

**Comment by titoBouzout** [comment]
Im getting this thing popping up in my project because you insist to install locally, which does not make any sense because is the only one project I have to manage, and is breaking things because the paths are too large

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'S:\\www\\asd\\.data\\compile\\node_modules\\grunt-contrib-uglify\\node_modules\\maxmin\\node_modules\\pretty-bytes\\node_modules\\meow\\node_modules\\normalize-package-data\\node_modules\\validate-npm-package-license\\node_modules\\spdx-correct\\node_modules\\spdx-license-ids\\*.*'

I'm gonna get ride of this non-sense-shiny-grunt-do-as-i-wish-gonna-be-obsolete-in-a-few-years-losing-time with a bunch of python scripts as soon as I have time.

**Comment by titoBouzout** [comment]
Thank you
