### ISSUE TITLE
Submodules using grunt.loadNpmTasks need to use their own node_modules directory

### ISSUE THREAD

**Issue by dylang** [gruntjs/grunt#696]
We needed the code in the `Gruntfile.js` to be easily updatable via npm and shared across projects so we put it in another module and pass `grunt` to that module something like this:

```
module.exports = function(grunt) {
  var gw = require('gruntwork');   
  gw(grunt, { someOptions: true });
};
```

By default code in **that module** (gruntwork) cannot use `grunt.loadNpmTasks` to load **its dependences** because it looks for them in the wrong place: relative to root of the parent project.

This can addressed by adding the keyword `gruntcollection` in the submodule's  `package.json`, however this causes errors because not all the dependencies are grunt tasks so they don't all have a task directory. `gruntcollection` seems to be only for modules that have ONLY grunt tasks as dependencies which seems like a good feature but not what we need in this case.

I think a better solution might also help make it easier to split up Gruntfiles into smaller reusable modules that have their own devdependencies.

**Comment by misak113** [comment]
I'm looking for solution of problem long time. After give up I wrote this method to solve: "Grunting node modules on npm install postinstall script":
```javascript
exports.loadParentNpmTasks = function (grunt, name) {
	var root = path.resolve('node_modules');
	var depth = 0;
	while (depth < 10) {
		var tasksdir = path.join(root, name, 'tasks');
		if (grunt.file.exists(tasksdir)) {
			grunt.loadNpmTasks(name);
			return;
		} else {
			name = '../../node_modules/' + name;
			depth++;
		}
	}
	grunt.log.error('Parent Npm module "' + name + '" not found. Is it installed?');
};
```
then usage:
```javascript
GruntConfiguration.loadParentNpmTasks(grunt, 'grunt-typescript');
// instead of
grunt.loadNpmTasks('grunt-typescript');
```
And package.json
```json
"scripts": {
    "postinstall": "grunt postinstall"
}
```
Hope it'll help you.

**Comment by SteveHarris** [comment]
trying to run code coverage of grunt tasks in development (developing actual grunt tasks) is an example where loading from alternate directory (such as you might get using require(...).addPath()) is necessary.  I currently have to copy ALL of my dev node_dependencies into an instrumented directory, and this is just a pain.

**Comment by gyandeeps** [comment]
I think with `nodejs 0.12.0` and `grunt 0.4.5`, this problem is resolved.

**Comment by asyncanup** [comment]
Really need this in one of our projects.
We're using grunt as part of a larger Eclipse project, and the node_modules folder can't be put in the same nested folder as Gruntfile because it makes the builds _extremely_ heavy and slow.
But do want to keep Gruntfile in the nested folder and run grunt from there since that's where the frontend code is.
I'm aware of the workarounds, but it's a big inconvenience.

**Comment by glenpike** [comment]
I'm with @qraynaud on this one.  I understand that it's bad practice to "globalise" dependencies _generally_, but we have tooling for lots of front-end applications based on node_modules.
Today, I ran into disk space issues on our CI server.  By sharing the node_modules directory, (I had to hack this because of an issue with load-grunt-tasks and our setup), I managed to reduce our footprint by 2G and at first glance, it appears to speed up our builds, etc. 

So we may be doing it _wrong_ according to some people, but I feel having this flexibility is a positive.

**Comment by qraynaud** [comment]
This was not fixed in 2 years of time? I'm so glad I switched to gulp/glou…

**Comment by jonschlinkert** [comment]
hey, great feedback @qraynaud! that's super helpful. btw can't find a link for "glou"... how did you switch to it?

**Comment by qraynaud** [comment]
Yeah, well. I'm disappointed, that might explain a lot ^^.

For glou, you can find it there : https://www.npmjs.com/package/glou

**Comment by binki** [comment]
So the only way to get `require()`-based task loading it to abandon grunt?

**Comment by brutalcrozt** [comment]
[How to load a task using loadNpmTask in gruntfile if module is in different directory](http://stackoverflow.com/questions/30175742/how-to-load-a-task-using-loadnpmtask-in-gruntfile-if-module-is-in-different-dire "SO question") i verify that the answer work
