### ISSUE TITLE
Ability to turn off "Cannot delete files outside the current working directory" warning

### ISSUE THREAD

**Issue by asgeo1** [gruntjs/grunt#803]
I'm using grunt to optimise/build a HTML5 mobile application, which I am distributing with Cordova/Phonegap.

I have set grunt to output the built files into the www directory of my Cordova project.

Unfortunately the Cordova www directory is located outside of the grunt project. So when the `grunt-contrib-clean` task runs, it throws a warning and halts:

```
Warning: Cannot delete files outside the current working directory. Use --force to continue.
```

(that warning is generated from file.js)

Can we please add an option so we can turn off this warning? Or perhaps just output the warning, but don't halt the job?

It's not great to have to use `--force` in order to run the task, as then any other errors in my build process get ignored.

**Comment by HolgerJeromin** [comment]
Just a note:
The message "Cannot delete files outside the current working directory" does NOT come from `grunt-contrib-clean` code but is generated by `grunt.file.delete` itself. 
So if someone (like me) googles the message this can be an own call to `grunt.file.delete` instead of a `grunt-contrib-clean` call.
