### ISSUE TITLE
Grunt LiveScript & CoffeeScript dependency strategy 

### ISSUE THREAD

**Issue by vladikoff** [gruntjs/grunt#911]
We need a way to make sure `Gruntfile.coffee` and `Gruntfile.ls` files keep up with the latest version of the "coffee-script" and "LiveScript" packages. However we also need to make sure that `Gruntfile.{ls,coffee}` works for everyone and doesn't cause issues on different environments. 

Some points of discussion:
* Updating CoffeeScript ( https://npmjs.org/package/coffee-script )
* Updating Grunt and updating LiveScript ( https://npmjs.org/package/LiveScript )
* Literate CoffeeScript support
* `coffee,litcoffee,coffee.md` support
* live-script and/or type-script support for Gruntfiles / tasks.

**Comment by dfernandez79** [comment]
@vladikoff I just saw comment in my PR referencing to this thread. (BTW Nice issue number!)

I don't see why this would break anything, even in the CoffeeScript changelog the only breaking change is to require register.

Why having to wait for the 0.5 Liftoff solution that requires a more involved rewrite? (the last message in the thread from May 2014!)

I understand that the Liftoff approach is better, since this really belongs to the grunt-cli rather than to the core. But I'm a little bit disapointed, because a one line fix adds value to your coffee users. So to me it makes sense to bump a small update rather leave the issue in the limbo for several months :(

For reference this is problematic when you have custom tasks in Coffee, or in projects that allows you to split your Gruntfile in several coffee files (like grunt-load-config). The old version of Coffee doesn't handle some identation cases very well.

**Comment by vladikoff** [comment]
@dfernandez79 this is up to @cowboy and @tkellen, not me.

**Comment by cryptoquick** [comment]
I hereby voice my support for this. :+1:

**Comment by cha0s** [comment]
Why hasn't this been bumped? Are you waiting for a PR that changes one line in package.json? Because I can provide a PR that changes one line in package.json

**Comment by shama** [comment]
Closing as `coffee-script` is now updated on `master`.

Going forward, we'll move towards [liftoff](https://github.com/js-cli/js-liftoff) which will enable support for additional languages and keeping dependencies more up to date. Look for an https://github.com/gruntjs/rfcs related to it soon (or open one if you would like to take on this endeavor sooner). Thanks!
