### ISSUE TITLE
When attempting to load a file from user's home directory (~) and receiving ENOENT

### ISSUE THREAD

**Issue by ckelner** [gruntjs/grunt#999]
My config looks something like:

```
grunt.initConfig({
   pkg: grunt.file.read('~/.file.properties'),
   ...
});
```

Which results in:

```
Error: Unable to read "~/.file.properties" file (Error code: ENOENT).
```

However if I use the full path:

```
grunt.initConfig({
   pkg: grunt.file.read('/Users/ckelner/.file.properties'),
   ...
});
```

It works as expected.

I need this to work across multiple machines and we've been using the user's home directory to store this file for sometime.  I was hoping to not need to change that for any reason.

Possibly something I am doing wrong, I don't know.

**Comment by nottinhill** [comment]
@vishaltelangre suggestion worked. No need for some library.

**Comment by vishaltelangre** [comment]
Cheers!

**Comment by arpitaprolix** [comment]
@vishaltelangre 
grunt.file.read(process.env['HOME'] + '/.file.properties')
It's work fine for me but I want to read like follwoing,

grunt.file.read( 'root/.file.properties')

So for getting root directory what should I have to do ?
I tried to finding that if any npm library available for getting root instead of HOME but can't getting. :(

Thanks in advance :)

**Comment by olimortimer** [comment]
Just want to thank @vishaltelangre for the `process.env['HOME']` suggestion - works perfectly
